Grant snap_sudo os group on t-linux-2404-wayland
mozilla-releng/fxci-config pull request #125
Opened 2024-09-30 18:56 UTC by jwmoss

2024-09-30 19:06 UTC, aerickson approved these changes

2024-10-01 07:49 UTC, jcristau requested changes
I don't think wildcards in the middle of a scope work, they need to be at the end (https://docs.taskcluster.net/docs/reference/platform/auth/scopes#stars-in-scopes)

2024-10-01 09:57 UTC, jwmoss commented
> I don't think wildcards in the middle of a scope work, they need to be at the end (https://docs.taskcluster.net/docs/reference/platform/auth/scopes#stars-in-scopes)

Mind checking again?

2024-10-01 09:58 UTC, jcristau approved these changes

2024-10-01 12:53 UTC, merged