Bug 1907169: improve regression in in_tree_action performance
mozilla-releng/fxci-config pull request #17
Opened 2024-07-11 15:34 UTC by bhearsum

Switching from `asyncio.gather` to individual `awaits` added a ton of overhead. Restoring `gather` usage required some refactoring, so I've split it out for easier reviewing.

This also drops a non-existant branch for product-details that I noticed, which I didn't think was worth splitting out.

Already reviewed in https://phabricator.services.mozilla.com/D216207

2024-07-11 15:35 UTC, jcristau requested changes
The commit message still references the projects.yml change that was moved to a separate patch.

2024-07-11 15:36 UTC, bhearsum commented
Probably failing because this depends on https://github.com/mozilla-releng/fxci-config/pull/16

2024-07-11 17:45 UTC, bhearsum commented
> Probably failing because this depends on #16

Looks like this is intermittent. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1907402 for it.

2024-07-12 10:59 UTC, jcristau approved these changes

2024-07-12 11:10 UTC, merged