bug 1907217: remove `*` branch from vpn and autoland repositories
mozilla-releng/fxci-config pull request #40
Opened 2024-07-21 18:49 UTC by bhearsum

Removing the `*` branch from RelEng Github repos and a twig worked fine. `mozilla-vpn-client` is the next step for Github, which uses release promotion actions and is higher activity. `autoland` is the next most safe place to do this on the hg side, as any issues should be noticed quite quickly.

2024-07-21 18:54 UTC, bhearsum commented
This patch has the effect of removing these roles from the fxci cluster:
* https://firefox-ci-tc.services.mozilla.com/auth/roles/repo%3Agithub.com%2Fmozilla-mobile%2Fmozilla-vpn-client%3Abranch%3A*
* https://firefox-ci-tc.services.mozilla.com/auth/roles/repo%3Agithub.com%2Fmozilla-releng%2Fstaging-mozilla-vpn-client%3Abranch%3A*
* https://firefox-ci-tc.services.mozilla.com/auth/roles/repo%3Ahg.mozilla.org%2Fintegration%2Fautoland%3Abranch%3A*

...which should be perfectly safe, because we have branch specific roles with the same scopes, such as [this](https://firefox-ci-tc.services.mozilla.com/auth/roles/repo%3Agithub.com%2Fmozilla-mobile%2Fmozilla-vpn-client%3Abranch%3Areleases%2F*) and [this](https://firefox-ci-tc.services.mozilla.com/auth/roles/repo%3Ahg.mozilla.org%2Fintegration%2Fautoland%3Abranch%3Adefault).

2024-07-23 07:20 UTC, jcristau requested changes
IMO we should be leaving the hg projects alone here.  While I don't foresee autoland getting non-default branch commits, I also don't think there's a meaningful distinction, e.g. access control is the same.

2024-07-23 14:18 UTC, bhearsum commented
> IMO we should be leaving the hg projects alone here. While I don't foresee autoland getting non-default branch commits, I also don't think there's a meaningful distinction, e.g. access control is the same.

I'm fine with that seeing as they're going away in the next 1-2 years.

2024-07-23 14:19 UTC, bhearsum commented
I re-added the `*` branch to `maple` for consistency.

2024-07-23 14:29 UTC, jcristau approved these changes
Update the commit message please :)

2024-07-23 15:27 UTC, merged